name: workout365app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

scripts:

  mobx_watch: flutter clean & flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs

  mobx_build: flutter clean & flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs


dependencies:
  pedantic: ^1.8.0+1
  flutter_cache_manager: ^1.4.2
  chewie: ^0.9.10
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.0.5
  bloc: ^6.0.3
  video_player: ^0.10.12+2
  vector_math: ^2.0.8
  clay_containers: ^0.2.2
  flutter_secure_storage: ^3.3.3
  intl: ^0.16.1
  flutter_masked_text: ^0.8.0
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.8
  flutter_dotenv: ^2.1.0
  flutter_screenutil: ^2.1.0
  smooth_star_rating: 1.1.1
  get: ^2.14.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter
  credit_card: ^0.1.6
  font_awesome_flutter: ^8.8.1
  swipedetector: ^1.2.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/images/Remada.gif
    - lib/assets/images/2.0x/logo_branco2x.png
    - lib/assets/images/logoNova.png
    - lib/assets/images/logoGrande.png
    - lib/assets/images/logoGrandeBranca.png
    - lib/assets/images/logoNovaPreto.png
    - lib/assets/images/halteres.jpg
    - lib/assets/images/Costas2.jpg
    - lib/assets/images/barra.jpg
    - lib/assets/images/apoio.jpg
    - lib/assets/images/triceps.jpg
    - lib/assets/images/Perna.jpg
    - lib/assets/images/Abdominal.jpg
    - lib/assets/images/Alongamento.jpg
    - lib/assets/images/Musculacao.png
    - lib/assets/images/Funcional.png
    - lib/assets/images/Cardio.png
    - lib/assets/images/k365.png
    - lib/assets/images/user.jpg
    - .env
    - .env_dev
#    - lib/assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
